from tkinter import *

top=Tk()
top.geometry("200x200")
#name = Label(top,text="Name").grid(row = 0,column=0)
#e1 = Entry(top).grid(row=0,column=1)
#pas =  Label(top,text="Password").grid(row = 1,column=0)
#e2 = Entry(top).grid(row=1,column=1)
#sub = Button(top,text="Submit").grid(row =2,column=1)
#place method()
#name1 = Label(top,text="Name").place(x=20,y=60)
#e3 = Entry(top).place(x=20,y=80)
#pas1= Label(top,text="Password").place(x=20,y=100)
#e4 = Entry(top).place(x=20,y=120)
red = Button(top,text="Red").pack(side=LEFT)
blue = Button(top,text="Blue").pack(side=RIGHT)
green = Button(top,text="Green").pack(side=TOP)
pink= Button(top,text="Pink").pack(side=BOTTOM)
top.mainloop()
